-- What a comment says, told from how it was typed.
--
-- A review comment is markdown, and until now it was drawn as the
-- characters it was written with: a link as `[the docs](https://…)`, a
-- heading as `## why`, `**must**` as two asterisks and a word, a table
-- as a row of pipes that line up only if its author lined them up. The
-- forge draws every one of them as something else, and the reviewer
-- reading them here is the one person on the merge request reading the
-- source of a page everybody else is reading rendered.
--
-- So this module reads a note the way the page does. It is a parser and
-- nothing else -- strings in, tables out, no editor state and no
-- colours of its own -- because the drawing is `nemeton.threads`'s and
-- has to be the same drawing in all four windows that do it. What comes
-- out is two shapes:
--
--   `M.blocks(lines)`  the note as the blocks it is written in: prose,
--                      a heading, a table, a suggestion, a fence.
--   `M.inline(line)`   one line as the runs it is drawn as, each
--                      carrying in `ref` what it points at -- which is
--                      what `<C-]>` follows -- and in `style` the
--                      weight it was written with.
--
-- Deliberately a subset. A comment on a merge request is a paragraph, a
-- link, a word somebody leant on, a list and now and then a table; a
-- markdown implementation is a fortnight, and every part of one that is
-- not those is a part that can be wrong about somebody's code review.
-- What is not recognised is drawn as it was typed, which is where the
-- whole plugin started.

local config = require("nemeton.config")

local M = {}

--- The sha a URL names, short, or nil for a URL that names no commit.
---
--- Both shapes the forge writes. `/-/commit/<sha>` is a commit of the
--- project; `merge_requests/N/diffs?commit_id=<sha>` is one of them as
--- this merge request shows it, which is what "copy link" gives you on
--- a row of the commit list you were reading. Eight digits because that
--- is the number GitLab itself prints -- the same string is on the row
--- the link came from.
---
--- Seven at least, or this is not a sha: a link to `/commit/main` names
--- a branch, and one to `/commit/HEAD` names wherever it has got to.
local function commit_sha(url)
  local sha = url:match("/commit/(%x+)") or url:match("[?&]commit_id=(%x+)")
  if sha and #sha >= 7 then
    return sha:sub(1, 8)
  end
  return nil
end

--- The comment a URL names, as the merge request it is on and the note
--- it is: two values, or nil for a URL that names no comment.
---
--- `#note_<id>` is the anchor GitLab's own "copy link" gives you on a
--- comment, on the merge request's page and on its diff alike, and it
--- is the only spelling there is: the forge has a short reference for
--- an issue, a merge request, a label and a user, and none for a note.
--- So this is what a reviewer pointing at another thread has pasted,
--- and it is what is worth reading as one.
---
--- The merge request as well as the note, because the id on its own
--- says nothing about which review it is in -- and a comment on
--- somebody else's merge request is a page to open rather than a thread
--- to walk to.
local function comment_at(url)
  local iid = url:match("/%-/merge_requests/(%d+)")
  local note = url:match("#note_(%d+)")
  if iid and note then
    return iid, note
  end
  return nil
end

--- What a comment is called, for a link to one whose author wrote no
--- words of their own over it.
---
--- A note permalink is a hundred characters of which twelve are the
--- content, and the same argument as `M.short_commits`: `!7 (comment
--- 1234)` says which review and which comment in what the forge calls
--- both, and the reader who wants the page has `<C-]>` to get to it.
--- The id is kept and not dropped, because a comment pointing at two
--- threads must not draw them as the same words.
---
--- What it is deliberately *not* is "alice on src/app.lua:42", which
--- this could say by asking the session what the id resolves to. Two
--- reasons, and either would do. It is the name the forge gives the
--- thing, so it is the same string on the page everybody else is
--- reading and the one a reviewer can say out loud; and a name that
--- came from resolving the id would be one this window could not draw
--- for a comment on another merge request, leaving the same link drawn
--- two ways depending on what happened to be open.
local function called(iid, note)
  return ("!%s (comment %s)"):format(iid, note)
end

--- Which sort of link a URL is: a page anywhere, or a page on this
--- forge written as the path to one.
---
--- GitLab writes the second itself -- an autogenerated reference to an
--- issue comes back as `/group/proj/-/issues/3` -- and a path opened in
--- a browser is a file that is not there. Two kinds rather than one so
--- that they can be followed differently: a page on the forge is part
--- of the review, and a link out of it is somebody else's website.
local function where(url)
  return url:match("^https?://") and "url" or "path"
end

--- Whether a link's text is the commit's own name rather than words
--- about it -- which is how GitLab writes one itself, and the one case
--- where keeping the text as well would print the sha twice.
local function names(text, sha)
  return text:match("^%x+$") ~= nil and sha:lower():find(text:lower(), 1, true) == 1
end

--- A note as it is drawn, with every link to a commit replaced by the
--- commit's short sha.
---
--- A permalink to a commit is a hundred characters whose only content
--- is the forty at the end of it. Left whole it wraps a two-line
--- comment across five and pushes what was said around it off the page;
--- as `a1b2c3d4` it says the same thing in what git would have called
--- it anyway, and the reviewer who wants the page has the sha to go to
--- it with.
---
--- Display only, and deliberately not done where a note is parsed:
--- rewriting one sends its body back to the forge, and a comment that
--- came home from a round trip through this window with its links taken
--- out of it is a comment the plugin has quietly damaged.
function M.short_commits(text)
  if type(text) ~= "string" or not config.comments.short_commits then
    return text
  end
  -- Markdown links first: the target inside one is a URL too, and taken
  -- in the other order the sha replaces it and leaves `[the fix](a1b2)`
  -- pointing at nothing. The text of the link is what the author chose
  -- to call the commit and is kept.
  text = text:gsub("%[([^%]\n]*)%]%((%S-)%)", function(label, url)
    local sha = commit_sha(url)
    if not sha then
      return nil
    end
    return (label == "" or names(label, sha)) and sha or ("%s (%s)"):format(label, sha)
  end)
  return (
    text:gsub("https?://%S+", function(url)
      -- What ends a sentence is not part of what it links to. Taken with
      -- the URL it would be swallowed by the sha that replaces it.
      local tail = url:match("[%.,;:!%?%)%]]+$") or ""
      local sha = commit_sha(url:sub(1, #url - #tail))
      if not sha then
        return nil
      end
      return sha .. tail
    end)
  )
end

-- The markers a comment is emphasised with, longest first: `***` is one
-- marker and not a `*` beside a `**`, and a scan that took the short one
-- first would leave a lone asterisk in the middle of somebody's
-- sentence.
--
-- `~~` and not `~`: a single tilde is a label reference on GitLab --
-- `~bug`, `~"needs work"` -- and the front of a path in half the
-- comments that mention one.
local EMPHASIS = {
  { "***", { "NemetonBold", "NemetonItalic" } },
  { "___", { "NemetonBold", "NemetonItalic" } },
  { "**", { "NemetonBold" } },
  { "__", { "NemetonBold" } },
  { "~~", { "NemetonStrike" } },
  { "*", { "NemetonItalic" } },
  { "_", { "NemetonItalic" } },
}

--- Whether a marker made of underscores is a marker at all.
---
--- `_` is the one of them that turns up inside words people write down:
--- `snake_case`, `TOKEN_2`, most of the URLs a review links to.
--- Markdown's own rule is that an underscore with a word character on
--- both sides emphasises nothing, and it is the rule that keeps a
--- variable name a variable name.
local function apart(text, from, to)
  if text:sub(from, from) ~= "_" then
    return true
  end
  local before = from > 1 and text:sub(from - 1, from - 1) or ""
  return not before:match("%w") or not text:sub(to + 1, to + 1):match("%w")
end

--- How far the run of `text:sub(at, at)` reaches -- `**` and `***` are
--- one delimiter each, and a scan that reads them a character at a time
--- closes `*a **b** c*` on the first half of the `**`.
local function run_of(text, at)
  local char = text:sub(at, at)
  local stop = at
  while text:sub(stop + 1, stop + 1) == char do
    stop = stop + 1
  end
  return stop
end

--- The marker opening at `at`, or nil. `taken` is the bytes a code span
--- has already claimed, where nothing is emphasis: the `*` in
--- `` `a * b` `` is a multiplication.
local function opens(text, at, taken)
  if taken[at] then
    return nil
  end
  for _, kind in ipairs(EMPHASIS) do
    local mark = kind[1]
    if text:sub(at, at + #mark - 1) == mark and apart(text, at, at + #mark - 1) then
      return mark, kind[2]
    end
  end
  return nil
end

--- Where the marker opened at `from` is closed, or nil for one that
--- never is -- a lone `*` in a sentence, which is a lone `*`.
---
--- Markdown's rules, cut to the two that matter here: an opener is
--- followed by something rather than by a space, and a closer follows
--- something rather than one. `2 * 3 * 4` is arithmetic and `a *b* c`
--- is emphasis, and that is the whole of the difference between them.
local function closes(text, taken, from, mark, stop)
  local after = from + #mark
  if after > stop or text:sub(after, after):match("%s") then
    return nil
  end
  local at = after
  while at <= stop do
    if text:sub(at, at) == mark:sub(1, 1) and not taken[at] then
      local last = run_of(text, at)
      if
        last - at + 1 == #mark
        and not text:sub(at - 1, at - 1):match("%s")
        and apart(text, at, last)
      then
        return at
      end
      at = last + 1
    else
      at = at + 1
    end
  end
  return nil
end

--- Every emphasised span of [from, stop], as the bytes its markers
--- occupy (`gone`) and the bytes they emphasise (`spans`).
---
--- Nested, and the inner span carries the outer's groups as well: the
--- word inside `**bold and *both* of it**` is bold and italic, and a
--- span that knew only about its own marker would come out italic
--- alone.
local function emphasis(text, taken, from, stop, groups, spans, gone)
  local at = from
  while at <= stop do
    local mark, adds = opens(text, at, taken)
    local close = mark and closes(text, taken, at, mark, stop)
    if close then
      local inner = vim.list_extend({}, groups or {})
      vim.list_extend(inner, adds)
      table.insert(gone, { at, at + #mark - 1 })
      table.insert(gone, { close, close + #mark - 1 })
      table.insert(spans, { from = at + #mark, to = close - 1, groups = inner })
      emphasis(text, taken, at + #mark, close - 1, inner, spans, gone)
      at = close + #mark
    else
      at = at + (mark and #mark or 1)
    end
  end
end

--- `runs` with the emphasis in them drawn as emphasis: the markers
--- gone, and every run they covered carrying the groups that say so in
--- `style`.
---
--- `style` and not the run's own colour, because emphasis is not one. A
--- bold word in a settled thread is dim and bold, a bold link is blue,
--- underlined and bold, and a group that carried a colour of its own
--- would flatten all three into whatever colour it was. What is drawn
--- is the colour that was already there with a weight put on top of it,
--- which is what the page does.
local function styled(runs)
  local parts, taken, at = {}, {}, 0
  for _, run in ipairs(runs) do
    if run.code then
      for i = at + 1, at + #run[1] do
        taken[i] = true
      end
    end
    at = at + #run[1]
    table.insert(parts, run[1])
  end
  local text = table.concat(parts)
  local spans, gone = {}, {}
  -- What was written down to *not* be a marker. A backslash in front of
  -- one is markdown's way of saying the character is the character, and
  -- with the marker now drawn as weight it is the only way left of
  -- writing an asterisk in a sentence about a glob. Only the three this
  -- module reads: `\n` in a comment about a string is a `\n`, and a
  -- path with backslashes in it is a path.
  local escaped = 1
  while escaped <= #text do
    if
      text:sub(escaped, escaped) == "\\"
      and not taken[escaped]
      and text:sub(escaped + 1, escaped + 1):match("[%*_~]")
    then
      table.insert(gone, { escaped, escaped })
      taken[escaped + 1] = true
      escaped = escaped + 2
    else
      escaped = escaped + 1
    end
  end
  emphasis(text, taken, 1, #text, nil, spans, gone)
  if #gone == 0 then
    return text, runs
  end
  -- Byte by byte, because a span is worked out over the whole line and
  -- the runs it lands on were cut by something else entirely: a link is
  -- one run, and `**see [the docs](url) first**` emphasises it and the
  -- words on either side of it.
  local groups, dropped = {}, {}
  for _, span in ipairs(spans) do
    for i = span.from, span.to do
      groups[i] = span.groups
    end
  end
  for _, mark in ipairs(gone) do
    for i = mark[1], mark[2] do
      dropped[i] = true
    end
  end
  local out, drawn = {}, {}
  at = 0
  for _, run in ipairs(runs) do
    local piece, style = {}, nil
    --- What has been gathered so far, as a run of its own.
    local function keep()
      if #piece > 0 then
        table.insert(out, { table.concat(piece), run[2], ref = run.ref, style = style })
      end
      piece = {}
    end
    for i = 1, #run[1] do
      local byte = at + i
      if not dropped[byte] then
        if groups[byte] ~= style then
          keep()
          style = groups[byte]
        end
        table.insert(piece, run[1]:sub(i, i))
      end
    end
    keep()
    at = at + #run[1]
  end
  for _, run in ipairs(out) do
    table.insert(drawn, run[1])
  end
  return table.concat(drawn), out
end

-- What a comment points at rather than says: a name somebody is being
-- called by, and a commit somebody is pointing at. Word-bounded, so an
-- email address is not a mention and a word in the middle of a sentence
-- is not a sha.
--
-- A sha needs a digit *and* a letter in it to count. Seven characters
-- of nothing but a-f is a word English happens to have -- "defaced",
-- "acceded" -- and seven of nothing but digits is a number somebody
-- wrote down; a commit is the thing that is both.
local REFERENCES = {
  { "@([%w][%w%._%-]*)", "mention", "NemetonMention" },
  {
    "(%x%x%x%x%x%x%x+)",
    "commit",
    "NemetonCommit",
    function(word)
      return #word <= 40 and word:match("%d") ~= nil and word:match("[a-fA-F]") ~= nil
    end,
  },
}

--- Whether the bytes [from, to) of `text` start a word: what stops
--- `theo@example` being a mention and `1a2b3c4dfix` being a commit.
local function bounded(text, from, to)
  local before = from > 1 and text:sub(from - 1, from - 1) or ""
  return not before:match("[%w_@%-%.]") and not text:sub(to + 1, to + 1):match("[%w_]")
end

--- The trailing punctuation of a URL, which is not part of it: what
--- ends a sentence a link is at the end of.
local function undotted(url)
  return url:sub(1, #url - #(url:match("[%.,;:!%?%)%]]+$") or ""))
end

--- One line of a comment as the runs it is drawn as: `{ text, hl }`,
--- with `ref` on the ones that point somewhere.
---
--- Returns the drawn text and those runs -- which concatenate back to
--- exactly it, so a caller can wrap the string and slice the colours to
--- match. The runs are nil where the line is drawn exactly as it was
--- typed with nothing on it to point at, which is most lines: a line
--- with one chunk on it is one chunk to slice, to measure and to draw.
---
--- What the drawn text is *not* is what is sent back. Rewriting a
--- comment posts the body its author wrote -- brackets, URLs and all --
--- because that is what the forge renders and what the next person to
--- edit it has to see.
function M.inline(text)
  if type(text) ~= "string" then
    return text, nil
  end
  local c = config.comments
  local found = {}

  --- Claims bytes [from, to] of the line, unless something with a
  --- better claim already has them. In the order they are looked for: a
  --- link owns the URL inside it, a URL owns the sha at the end of it,
  --- and neither is a mention of anybody.
  local function claim(from, to, drawn, hl, ref, code)
    for _, taken in ipairs(found) do
      if from <= taken.to and to >= taken.from then
        return
      end
    end
    table.insert(found, { from = from, to = to, text = drawn, hl = hl, ref = ref, code = code })
  end

  -- `` `a_b` `` first, and before anything else looks at the line: what
  -- is inside a code span is text and not markup. A URL in one is not a
  -- link to be followed, an `@name` in one is not somebody to notify,
  -- and the underscores in one are part of an identifier. The forge
  -- draws it as the words without the backticks, in a colour that says
  -- it is code, which is what the backticks were for.
  --
  -- A run of them closes on a run of the same length, so `` `a` `` is
  -- how you write a backtick down.
  if c.styles then
    local at = 1
    while true do
      local from, to = text:find("`+", at)
      if not from then
        break
      end
      at = to + 1
      local close, last = text:find("`+", at)
      while close and last - close + 1 ~= to - from + 1 do
        close, last = text:find("`+", last + 1)
      end
      if close and close > to + 1 then
        claim(from, last, text:sub(to + 1, close - 1), "NemetonCode", nil, true)
        at = last + 1
      end
    end
  end

  -- `[what it is called](where it goes)`, drawn as what it is called.
  --
  -- The URL is the half nobody reads and two thirds of the width: a
  -- sentence with three links in it is drawn as three hundred columns
  -- of protocol and path, wrapped across five lines, with the words
  -- somebody wrote scattered between them. The link keeps where it
  -- goes -- in `ref`, for the key that follows it -- and gives up the
  -- room.
  if c.links then
    local at = 1
    while true do
      local from, to, label, url = text:find("%[([^%]\n]*)%]%((%S-)%)", at)
      if not from then
        break
      end
      at = to + 1
      -- `![alt](src)` is a picture, which a terminal has nowhere to
      -- put: it is drawn as what its author said it was, and the `!`
      -- that made it a picture goes with the brackets.
      local image = from > 1 and text:sub(from - 1, from - 1) == "!"
      local iid, note = comment_at(url)
      local sha = commit_sha(url)
      -- The comment before the commit: a link to a thread on a diff
      -- carries the commit it was written against as well
      -- (`…/diffs?commit_id=…#note_12`), and what its author was
      -- pointing at is the argument and not the push.
      if iid then
        -- The `!` of a picture goes with the brackets here too, absurd
        -- as a picture of somebody's comment would be.
        claim(
          image and from - 1 or from,
          to,
          label ~= "" and label or called(iid, note),
          "NemetonLink",
          {
            kind = "thread",
            text = note,
            iid = tonumber(iid),
            href = url,
          }
        )
      elseif sha and c.short_commits then
        claim(
          from,
          to,
          (label == "" or names(label, sha)) and sha or label,
          "NemetonCommit",
          { kind = "commit", text = sha, href = url }
        )
      else
        local drawn = label
        if drawn == "" then
          drawn = image and "image" or url
        end
        claim(image and from - 1 or from, to, drawn, "NemetonLink", {
          kind = where(url),
          text = label,
          href = url,
        })
      end
    end
  end

  -- ...and a URL written on its own, which is a link whose text is
  -- where it goes.
  local at = 1
  while true do
    local from, to = text:find("https?://%S+", at)
    if not from then
      break
    end
    at = to + 1
    local url = undotted(text:sub(from, to))
    local iid, note
    if c.links then
      iid, note = comment_at(url)
    end
    local sha = c.short_commits and commit_sha(url)
    if iid then
      claim(from, from + #url - 1, called(iid, note), "NemetonLink", {
        kind = "thread",
        text = note,
        iid = tonumber(iid),
        href = url,
      })
    elseif sha then
      claim(from, from + #url - 1, sha, "NemetonCommit", {
        kind = "commit",
        text = sha,
        href = url,
      })
    elseif c.links then
      claim(
        from,
        from + #url - 1,
        url,
        "NemetonLink",
        { kind = where(url), text = url, href = url }
      )
    end
  end

  if c.references then
    for _, kind in ipairs(REFERENCES) do
      local from, to, word
      at = 1
      while true do
        from, to, word = text:find(kind[1], at)
        if not from then
          break
        end
        at = to + 1
        if bounded(text, from, to) and (not kind[4] or kind[4](word)) then
          claim(from, to, text:sub(from, to), kind[3], { kind = kind[2], text = word })
        end
      end
    end
  end

  table.sort(found, function(a, b)
    return a.from < b.from
  end)
  local runs, cursor = {}, 1
  for _, mark in ipairs(found) do
    if mark.from > cursor then
      table.insert(runs, { text:sub(cursor, mark.from - 1) })
    end
    table.insert(runs, { mark.text, mark.hl, ref = mark.ref, code = mark.code })
    cursor = mark.to + 1
  end
  if cursor <= #text then
    table.insert(runs, { text:sub(cursor) })
  end
  if #runs == 0 then
    runs = { { text } }
  end
  -- ...and the weight the words are drawn with, which is worked out
  -- over the line as it is drawn rather than as it was typed: the
  -- asterisks around `**[the docs](url)**` are around what the link is
  -- called by the time anything can be emphasised.
  local drawn, out
  if c.styles then
    drawn, out = styled(runs)
  else
    local parts = {}
    for _, run in ipairs(runs) do
      table.insert(parts, run[1])
    end
    drawn, out = table.concat(parts), runs
  end
  if #found == 0 and out == runs then
    -- Nothing found and nothing emphasised: a line with one chunk on it
    -- is one chunk to slice, to measure and to draw.
    return text, nil
  end
  return drawn, out
end

--- A whole body as it is drawn, as one string: what the windows that
--- show a comment as a single line want, where there is no room for
--- colours and nothing to follow a link with.
function M.plain(text)
  if type(text) ~= "string" then
    return text
  end
  local out = {}
  for _, line in ipairs(vim.split(text, "\n", { plain = true })) do
    table.insert(out, (M.inline(line)))
  end
  return table.concat(out, "\n")
end

--- The cells of a table row, or nil for a line that is not one.
---
--- The outer pipes are optional in markdown and usually written; either
--- way what is between them is the row. A cell is trimmed, because the
--- spaces around it are how its author lined the source up and not
--- anything they wrote.
local function cells(line)
  if not line:find("|", 1, true) then
    return nil
  end
  local out = {}
  for cell in (vim.trim(line):gsub("^|", ""):gsub("|%s*$", "") .. "|"):gmatch("(.-)|") do
    table.insert(out, vim.trim(cell))
  end
  return out
end

--- The alignments a delimiter row asks for -- `:---`, `---:`, `:---:`
--- -- or nil for a row that is not one. It is the line that makes a
--- table a table: pipes on their own are a sentence about a shell.
local function alignments(line)
  local row = line and cells(line)
  if not row or #row == 0 then
    return nil
  end
  local out = {}
  for i, cell in ipairs(row) do
    local left, right = cell:match("^(:?)%-%-*(:?)$")
    if not left then
      return nil
    end
    out[i] = (left == ":" and right == ":" and "center") or (right == ":" and "right") or "left"
  end
  return out
end

--- A prose line with its hard break taken off the end of it.
---
--- A backslash at the end of a line is markdown for "and the next line
--- goes underneath this one" -- which is what these windows do with
--- every line of a comment anyway, since a note is drawn as the lines
--- it was typed in. So the mark itself is not drawn: it did its work in
--- the source, and left whole it is a stray backslash at the end of
--- somebody's sentence.
---
--- Only where there is a line under it to break to. A backslash at the
--- end of a paragraph broke nothing and is a backslash its author
--- typed, and an even number of them is an escaped backslash and not a
--- break at all.
local function broken(line, next_line)
  if not next_line or vim.trim(next_line) == "" then
    return line
  end
  local slashes = line:match("\\*$") or ""
  if #slashes % 2 == 0 then
    return line
  end
  return line:sub(1, #line - 1)
end

--- The lines of a note, as the blocks it is written in.
---
--- One pass, and greedy: a fence swallows everything up to the next
--- one, a table swallows every row under its head. What is left is
--- prose, a line at a time, which is what a comment mostly is.
---
--- Each block is `{ kind = ... }` and carries what its kind needs:
---
---   prose       `text`
---   heading     `text`, `level`
---   table       `rows` (the head first), `align`
---   suggestion  `lines`, `above`, `below`, `fence`, `close`
---   code        `lines`, `fence`, `close`
---
--- A fence nobody closed is applied anyway, with `close` nil -- which
--- is what GitLab does with one, and what one looks like while it is
--- still being typed.
function M.blocks(lines)
  local c = config.comments
  local out, i = {}, 1
  while i <= #lines do
    local line = lines[i]
    local fence = line:match("^%s*```(.*)$")
    local heading, said = line:match("^(#+)%s+(.*)$")
    local align = c.tables and alignments(lines[i + 1]) or nil
    if fence then
      local body, close, j = {}, nil, i + 1
      while j <= #lines do
        if lines[j]:match("^%s*```") then
          close = lines[j]
          break
        end
        table.insert(body, lines[j])
        j = j + 1
      end
      if fence:match("^suggestion") then
        table.insert(out, {
          kind = "suggestion",
          lines = body,
          fence = line,
          close = close,
          -- `suggestion:-N+M` is "this line, the N above it and the M
          -- below" -- counted from the line the thread is anchored to.
          above = tonumber(fence:match("%-(%d+)")) or 0,
          below = tonumber(fence:match("%+(%d+)")) or 0,
        })
      else
        table.insert(out, { kind = "code", lines = body, fence = line, close = close })
      end
      i = j + 1
    elseif heading and c.headings and #heading <= 6 then
      table.insert(out, { kind = "heading", text = said, level = #heading })
      i = i + 1
    elseif align and cells(line) then
      local rows = { cells(line) }
      local j = i + 2
      while j <= #lines and cells(lines[j]) do
        table.insert(rows, cells(lines[j]))
        j = j + 1
      end
      table.insert(out, { kind = "table", rows = rows, align = align })
      i = j
    else
      table.insert(out, { kind = "prose", text = broken(line, lines[i + 1]) })
      i = i + 1
    end
  end
  return out
end

return M
