local Expression = require("nvim-dap-df-pane.expression")

describe("Expression", function()
	describe("new()", function()
		it("stores the base expression", function()
			local b = Expression:new("df")
			assert.equals("df", b:get_base_expr())
		end)

		it("starts with no sort and no filters", function()
			local b = Expression:new("df")
			assert.is_nil(b:get_sort())
			assert.same({}, b:get_filters())
		end)
	end)

	describe("build()", function()
		it("returns the base expression when no sort or filter is set", function()
			local b = Expression:new("df.head(100)")
			assert.equals("df.head(100)", b:build())
		end)
	end)

	describe("set_filter()", function()
		it("stores a filter under the column name for regular columns", function()
			local b = Expression:new("df")
			b:set_filter("age", false, "> 5")
			assert.equals("> 5", b:get_filter("age", false))
		end)

		it("stores a filter under 'index' for the index column", function()
			local b = Expression:new("df")
			b:set_filter("my_index", true, "> 0")
			-- Retrieval must use is_index=true regardless of the column's display name
			assert.equals("> 0", b:get_filter("my_index", true))
			assert.equals("> 0", b:get_filter("anything", true))
		end)

		it("treats regular and index columns as distinct", function()
			local b = Expression:new("df")
			b:set_filter("age", false, "> 5")
			b:set_filter("age", true, "> 10")
			assert.equals("> 5", b:get_filter("age", false))
			assert.equals("> 10", b:get_filter("age", true))
		end)

		it("clears the filter when given an empty condition", function()
			local b = Expression:new("df")
			b:set_filter("age", false, "> 5")
			b:set_filter("age", false, "")
			assert.is_nil(b:get_filter("age", false))
		end)

		it("build() wraps the expression with a .query() call", function()
			local b = Expression:new("df")
			b:set_filter("age", false, "> 5")
			assert.equals([[(df).query("`age` > 5", engine='python')]], b:build())
		end)

		it("build() accepts shorthand '= value' as ==", function()
			local b = Expression:new("df")
			b:set_filter("name", false, "= 'foo'")
			assert.equals([[(df).query("`name` == 'foo'", engine='python')]], b:build())
		end)

		it("build() defaults to == when the condition has no operator prefix", function()
			local b = Expression:new("df")
			b:set_filter("name", false, "'foo'")
			assert.equals([[(df).query("`name` == 'foo'", engine='python')]], b:build())
		end)

		it("build() leaves method-style conditions untouched", function()
			local b = Expression:new("df")
			b:set_filter("name", false, ".str.contains('foo')")
			assert.equals(
				[[(df).query("`name` .str.contains('foo')", engine='python')]],
				b:build()
			)
		end)

		it("build() expands bare comparisons after and/or", function()
			local b = Expression:new("df")
			b:set_filter("age", false, "> 5 and < 20")
			assert.equals(
				[[(df).query("`age` > 5 and `age` < 20", engine='python')]],
				b:build()
			)
		end)
	end)

	describe("clear_filter()", function()
		it("removes the filter on a column", function()
			local b = Expression:new("df")
			b:set_filter("age", false, "> 5")
			b:clear_filter("age", false)
			assert.is_nil(b:get_filter("age", false))
		end)

		it("is a no-op when no filter is set", function()
			local b = Expression:new("df")
			assert.has_no.errors(function()
				b:clear_filter("age", false)
			end)
		end)
	end)

	describe("toggle_sort()", function()
		it("first toggle sets ascending sort", function()
			local b = Expression:new("df")
			b:toggle_sort("age", false)
			local sort = b:get_sort()
			assert.is_not_nil(sort)
			assert.equals("age", sort.col_name)
			assert.is_false(sort.is_index)
			assert.is_true(sort.ascending)
		end)

		it("second toggle on the same column flips to descending", function()
			local b = Expression:new("df")
			b:toggle_sort("age", false)
			b:toggle_sort("age", false)
			assert.is_false(b:get_sort().ascending)
		end)

		it("third toggle on the same column clears the sort", function()
			local b = Expression:new("df")
			b:toggle_sort("age", false)
			b:toggle_sort("age", false)
			b:toggle_sort("age", false)
			assert.is_nil(b:get_sort())
		end)

		it("toggling a different column resets to ascending on that column", function()
			local b = Expression:new("df")
			b:toggle_sort("age", false)
			b:toggle_sort("age", false) -- now descending
			b:toggle_sort("name", false)
			local sort = b:get_sort()
			assert.equals("name", sort.col_name)
			assert.is_true(sort.ascending)
		end)

		it("regular and index columns are treated as distinct", function()
			local b = Expression:new("df")
			b:toggle_sort("age", false)
			b:toggle_sort("age", true)
			local sort = b:get_sort()
			assert.is_true(sort.is_index)
			assert.is_true(sort.ascending)
		end)

		it("build() appends sort_values for regular columns", function()
			local b = Expression:new("df")
			b:toggle_sort("age", false)
			assert.equals([[(df).sort_values("age", ascending=True)]], b:build())
		end)

		it("build() uses sort_index for the index column", function()
			local b = Expression:new("df")
			b:toggle_sort("any_name", true)
			assert.equals("(df).sort_index(ascending=True)", b:build())
		end)

		it("build() encodes descending as ascending=False", function()
			local b = Expression:new("df")
			b:toggle_sort("age", false)
			b:toggle_sort("age", false)
			assert.equals([[(df).sort_values("age", ascending=False)]], b:build())
		end)
	end)

	describe("build() with combined filters and sort", function()
		it("applies filter(s) before sort", function()
			local b = Expression:new("df")
			b:set_filter("age", false, "> 5")
			b:toggle_sort("name", false)
			assert.equals(
				[[((df).query("`age` > 5", engine='python')).sort_values("name", ascending=True)]],
				b:build()
			)
		end)
	end)
end)
